--============================
--
-- CHANGES:
--  - Changed CCAddress to CCZip in credit_card.
--  - Allowed SAName and CCNumber to be NULL in cart when the cart is still
--    active.
--  - Status in user is an integer value (0 = Regular, 1 = Silver, 2 = Gold,
--    3 = Platinum).
--
--============================

-- CUSTOMER table.
CREATE TABLE customer (
  CID INTEGER PRIMARY KEY AUTOINCREMENT,
  FName TEXT NOT NULL,
  LName TEXT NOT NULL,
  Email TEXT UNIQUE NOT NULL,
  Address TEXT DEFAULT NULL,
  Phone TEXT DEFAULT '',
  Status INTEGER DEFAULT 0,

  FOREIGN KEY(CID, Address) REFERENCES shipping_address(CID, SAName) ON DELETE SET NULL
);

-- SILVER_AND_ABOVE table.
CREATE TABLE silver_and_above (
  CID INTEGER PRIMARY KEY,
  CreditLine NUMERIC NOT NULL,
  
  FOREIGN KEY(CID) REFERENCES customer(CID) ON DELETE CASCADE
);

-- SHIPPING_ADDRESS table.
CREATE TABLE shipping_address (
  CID INTEGER NOT NULL,
  SAName TEXT NOT NULL,
  RecipientName TEXT NOT NULL,
  Street TEXT NOT NULL,
  SNumber INTEGER NOT NULL,
  City TEXT NOT NULL,
  Zip TEXT NOT NULL,
  State TEXT NOT NULL,
  Country TEXT NOT NULL,
  
  PRIMARY KEY(CID, SAName),
  FOREIGN KEY(CID) REFERENCES customer(CID) ON DELETE NO ACTION
);

-- CREDIT_CARD table.
CREATE TABLE credit_card (
  CCNumber TEXT PRIMARY KEY,
  SecNumber TEXT NOT NULL,
  OwnerName TEXT NOT NULL,
  CCType TEXT NOT NULL,
  CCZip TEXT NOT NULL,
  CCDate TEXT NOT NULL
);

-- STORED_CARD table.
CREATE TABLE stored_card (
  CCNumber TEXT PRIMARY KEY,
  CID INTEGER,
  
  FOREIGN KEY(CCNumber) REFERENCES credit_card(CCNumber) ON DELETE CASCADE,
  FOREIGN KEY(CID) REFERENCES customer(CID) ON DELETE CASCADE
);

-- CART table.
CREATE TABLE cart (
  CartID INTEGER PRIMARY KEY AUTOINCREMENT,
  CID NUMERIC NOT NULL,
  SAName TEXT DEFAULT NULL,
  CCNumber TEXT DEFAULT NULL,
  TStatus TEXT NOT NULL DEFAULT 'Open',
  TDate INTEGER DEFAULT NULL,
  
  FOREIGN KEY(CID, SAName) REFERENCES shipping_address(CID, SAName) ON DELETE NO ACTION,
  FOREIGN KEY(CCNumber) REFERENCES credit_card(CCNumber) ON DELETE NO ACTION
);

-- PRODUCT table.
CREATE TABLE product (
  PID INTEGER PRIMARY KEY AUTOINCREMENT,
  PType TEXT NOT NULL,
  PName TEXT NOT NULL,
  PPrice NUMERIC NOT NULL,
  PDescription TEXT NOT NULL,
  PQuantity INTEGER DEFAULT 0
);

-- APPEARS_IN table.
CREATE TABLE appears_in (
  CartID INTEGER NOT NULL,
  PID INTEGER NOT NULL,
  Quantity INTEGER NOT NULL,
  PriceSold NUMERIC NOT NULL,
  
  PRIMARY KEY (CartID, PID),
  FOREIGN KEY(CartID) REFERENCES cart(CardID) ON DELETE NO ACTION,
  FOREIGN KEY(PID) REFERENCES product(PID) ON DELETE NO ACTION
);

-- OFFER_PRODUCT table.
CREATE TABLE offer_product (
  PID INTEGER PRIMARY KEY,
  OfferPrice NUMERIC NOT NULL,
  
  FOREIGN KEY(PID) REFERENCES product(PID) ON DELETE CASCADE
);

-- COMPUTER table.
CREATE TABLE computer (
  PID INTEGER PRIMARY KEY,
  CPUType TEXT NOT NULL,
  
  FOREIGN KEY(PID) REFERENCES product(PID) ON DELETE CASCADE
);

-- LAPTOP table.
CREATE TABLE laptop (
  PID INTEGER PRIMARY KEY,
  BType TEXT NOT NULL,
  Weight INTEGER NOT NULL,
  
  FOREIGN KEY(PID) REFERENCES computer(PID) ON DELETE CASCADE
);

-- PRINTER table.
CREATE TABLE printer (
  PID INTEGER PRIMARY KEY,
  PrinterType TEXT NOT NULL,
  Resolution TEXT NOT NULL,
  
  FOREIGN KEY(PID) REFERENCES product(PID) ON DELETE CASCADE
);
