--############################
--
-- Notes:
--  - Removed address field from customer and credit_card as it's not used.
--
--############################

-- CUSTOMER table.
CREATE TABLE customer (
  CID INTEGER PRIMARY KEY AUTOINCREMENT,
  FName TEXT DEFAULT '',
  LName TEXT DEFAULT '',
  Email TEXT UNIQUE NOT NULL,
  Status TEXT DEFAULT 'Regular'
);

-- SILVER_AND_ABOVE table.
CREATE TABLE silver_and_above (
  CID INTEGER PRIMARY KEY,
  CreditLine NUMERIC NOT NULL,
  FOREIGN KEY(CID) REFERENCES customer(CID) ON DELETE CASCADE
);

-- SHIPPING_ADDRESS table.
CREATE TABLE shipping_address (
  CID INTEGER PRIMARY KEY,
  SAName TEXT PRIMARY KEY,
  RecepientName TEXT NOT NULL,
  Street TEXT NOT NULL,
  SNumber INTEGER NOT NULL,
  City TEXT NOT NULL,
  Zip NUMERIC NOT NULL,
  State TEXT NOT NULL,
  Country TEXT NOT NULL,
  FOREIGN KEY(CID) REFERENCES customer(CID) ON DELETE CASCADE
);

-- CREDIT_CARD table.
CREATE TABLE credit_card (
  CCNumber NUMERIC PRIMARY KEY,
  SecNumber NUMERIC NOT NULL,
  OwnerName TEXT NOT NULL,
  CCType TEXT NOT NULL,
  CCDate NUMERIC NOT NULL
);

-- STORED_CARD table.
CREATE TABLE stored_card (
  CCNumber NUMERIC PRIMARY KEY,
  CID INTEGER,
  FOREIGN KEY(CCNumber) REFERENCES credit_card(CCNumber) ON DELETE CASCADE,
  FOREIGN KEY(CID) REFERENCES customer(CID) ON DELETE CASCADE
);

-- CART table.
CREATE TABLE cart (
  CartID INTEGER PRIMARY KEY AUTOINCREMENT,
  CID NUMERIC NOT NULL,
  SAName TEXT NOT NULL,
  CCNumber NUMERIC NOT NULL,
  TStatus TEXT NOT NULL DEFAULT 'Open',
  TDate NUMERIC,
  FOREIGN KEY(CID, SAName) REFERENCES shipping_address(CID, SAName) ON DELETE CASCADE,
  FOREIGN KEY(CCNumber) REFERENCES credit_card(CCNumber) ON DELETE CASCADE
);

-- PRODUCT table.
CREATE TABLE product (
  PID INTEGER PRIMARY KEY AUTOINCREMENT,
  PType TEXT NOT NULL,
  PName TEXT NOT NULL,
  PPrice NUMERIC NOT NULL,
  PDescription TEXT NOT NULL,
  PQuantity INTEGER DEFAULT 0
);

-- APPEARS_IN table.
CREATE TABLE appears_in (
  CartID INTEGER PRIMARY KEY,
  PID INTEGER PRIMARY KEY,
  Quantity INTEGER NOT NULL,
  PriceSold NUMERIC NOT NULL
  FOREIGN KEY(CartID) REFERENCES cart(CardID) ON DELETE CASCADE,
  FOREIGN KEY(PID) REFERENCES product(PID) ON DELETE CASCADE
);

-- OFFER_PRODUCT
CREATE TABLE offer_product (
  PID INTEGER PRIMARY KEY,
  OfferPrice NUMERIC NOT NULL,
  FOREIGN KEY(PID) REFERENCES product(PID) ON DELETE CASCADE
);

-- COMPUTER table.
CREATE TABLE computer (
  PID INTEGER PRIMARY KEY,
  CPUType TEXT NOT NULL,
  FOREIGN KEY(PID) REFERENCES product(PID) ON DELETE CASCADE
);

-- LAPTOP table.
CREATE TABLE laptop (
  PID INTEGER PRIMARY KEY,
  BType TEXT NOT NULL,
  Weight INTEGER NOT NULL
  FOREIGN KEY(PID) REFERENCES computer(PID) ON DELETE CASCADE
);

-- PRINTER table.
CREATE TABLE printer (
  PID INTEGER PRIMARY KEY,
  PrinterType TEXT NOT NULL,
  Resolution INTEGER NOT NULL,
  FOREIGN KEY(PID) REFERENCES product(PID) ON DELETE CASCADE
);
